// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Backend.Entities.Users.Tbl_Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Access");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Access = "View Module 1"
                        },
                        new
                        {
                            Id = 2,
                            Access = "Add Module 1"
                        },
                        new
                        {
                            Id = 3,
                            Access = "Edit Module 1"
                        });
                });

            modelBuilder.Entity("Backend.Entities.Users.Tbl_Grant_Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("UserId");

                    b.ToTable("Tbl_Grant_Access");
                });

            modelBuilder.Entity("Backend.Entities.Users.Tbl_Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datetime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Error_id")
                        .HasColumnType("int");

                    b.Property<string>("Log_message")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Log_type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tbl_Logs");
                });

            modelBuilder.Entity("Backend.Entities.Users.Tbl_Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Access")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tbl_Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Access = "SuperAdmin",
                            Email = "mark@skybest.com.ph",
                            Firstname = "Mark",
                            Lastname = "San Juan",
                            Password = "skyMark01",
                            Status = true,
                            Username = "mackyboi"
                        },
                        new
                        {
                            Id = 2,
                            Access = "SuperAdmin",
                            Email = "joshua.suba@skybest.com.ph",
                            Firstname = "Joshua",
                            Lastname = "Suba",
                            Password = "skyJoshua01",
                            Status = true,
                            Username = "jsuba"
                        },
                        new
                        {
                            Id = 3,
                            Access = "SuperAdmin",
                            Email = "norwin.nabong@gmail.com.ph",
                            Firstname = "Norwin",
                            Lastname = "Nabong",
                            Password = "skyNorwin01",
                            Status = true,
                            Username = "nnabong"
                        },
                        new
                        {
                            Id = 4,
                            Access = "SuperAdmin",
                            Email = "dan.delatorre@skybest.com.ph",
                            Firstname = "Dan Cedrick",
                            Lastname = "Dela Torre",
                            Password = "skyDan01",
                            Status = true,
                            Username = "DTorre"
                        });
                });

            modelBuilder.Entity("Backend.Entities.Users.Tbl_Grant_Access", b =>
                {
                    b.HasOne("Backend.Entities.Users.Tbl_Access", "Access")
                        .WithMany()
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Entities.Users.Tbl_Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Entities.Users.Tbl_Logs", b =>
                {
                    b.HasOne("Backend.Entities.Users.Tbl_Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
