//Users CRUD
### All Users
GET http://localhost:5209/user

###
GET http://localhost:5209/user/nnabong/login
Content-Type: application/json

### Add User
POST http://localhost:5209/user
Content-Type: application/json

{
"Firstname": "Norwin",
"Lastname" : "Nabong",
"Email" : "norwin.nabong@skybest.com.ph",
"Username" : "nnabong01",
"Password" : "skyNorwin01",
"Access" : "",
"Status" : true
}

###
POST http://localhost:5209/user/register
Content-Type: application/json

{
    "Firstname": "Norwin",
    "Lastname": "Nabong",
    "Email": "Norwin.Nabong@skybest.com.ph",
    "Username": "nnabong",
    "Password": "skyNorwin01"
}

###
GET http://localhost:5209/user/login
Content-Type: application/json

{
    "UsernameOrEmail": "nnabong",
    "Password": "skyNorwin01"
}