//Users CRUD
### All Users
GET http://localhost:5209/user

###
GET http://localhost:5209/user/nnabong/login
Content-Type: application/json

### Add User
POST http://localhost:5209/user
Content-Type: application/json

{
"Firstname": "Norwin",
"Lastname" : "Nabong",
"Email" : "norwin.nabong@skybest.com.ph",
"Username" : "nnabong01",
"Password" : "skyNorwin01",
"Access" : "",
"Status" : true
}